version: "3"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: scavenge
      POSTGRES_PASSWORD: scavenge
      POSTGRES_DB: scavenge_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - /Users/sam/Workspace/go/scavenge/postgres/.psqlrc:/var/lib/postgresql/.psqlrc

volumes:
  pgdata:
